# Generated by Django 5.2 on 2025-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
