# Generated by Django 5.2 on 2025-04-25 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="status",
        ),
    ]
